'use client';
import { useState } from 'react';
import { Download, Mail, Plus, X, Loader2, FileText } from 'lucide-react';
import { getStatementWorkspace, getStatement, statementAction, downloadStatement, type StatementWorkspace, type Statement, type StatementDetail } from '@/modules/estados-prospectadores/service';
const labels = { pendiente: 'Pendiente de envío', enviado: 'Enviado', pagado: 'Pagado' };
const money = (v: string | number) => Number(v).toLocaleString('es-MX', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const month = (v: string) => new Intl.DateTimeFormat('es-MX', {month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(v+'T12:00:00Z'));
const button = 'inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed';
const secondary = 'inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50';
const input = 'w-full rounded-lg border border-slate-300 bg-white p-2.5 text-slate-900';
export function ProspectorStatementsView({ initial }: { initial: StatementWorkspace }) {
  const [data,setData] = useState(initial);
  const [period,setPeriod] = useState(initial.periods[0]?.id || '');
  const [filter,setFilter] = useState(''); const [statusFilter,setStatusFilter] = useState('');
  const [selected,setSelected] = useState<string[]>([]); const [busy,setBusy] = useState('');
  const [error,setError] = useState(''); const [message,setMessage] = useState('');
  const [edit,setEdit] = useState<StatementDetail | null>(null);
  const [targets,setTargets] = useState<Statement[] | null>(null);
  const [manual,setManual] = useState('');
  const [sendResults,setSendResults] = useState<{name:string;result:string}[]>([]);
  const rows = data.statements.filter(x=>x.period_id===period).sort((a,b)=>a.name.localeCompare(b.name));
  const visible = rows.filter(x=>(!statusFilter || x.status===statusFilter) && x.name.toLowerCase().includes(filter.toLowerCase()));
  const selectable = visible.filter(x=>x.prospector_active && x.status!=='pagado');
  const selectedRows = rows.filter(x=>x.prospector_active && x.status!=='pagado' && selected.includes(x.id));
  const allSelected = selectable.length>0 && selectable.every(x=>selected.includes(x.id));
  async function reload() { setData(await getStatementWorkspace()); }
  async function run(key:string, action:()=>Promise<void>) {
    setBusy(key);setError('');setMessage('');
    try { await action(); } catch(e) {setError(e instanceof Error?e.message:'No se pudo completar la operación.');}
    finally {setBusy('');}
  }
  async function generate(prospector_id?:string) { await run('generate',async()=>{
    const r=await statementAction<{created:number;updated:number}>('generate',{period_id:period,prospector_id});
    await reload();setManual('');setMessage(`${r.created} estados creados y ${r.updated} actualizados. Los ajustes manuales se conservaron.`);
  }); }
  async function open(id:string) {await run('open',async()=>{setEdit(await getStatement(id));});}
  async function save() {if(!edit)return;await run('save',async()=>{
    const updated=await statementAction<StatementDetail>(edit.id,{revision:edit.revision,recipient:edit.recipient,notes:edit.notes,adjustments:edit.adjustments,manual_commissions:edit.lines.filter(x=>x.manual).map(x=>({id:x.id,policy:x.policy,date:x.date,insurer:x.insurer,branch:x.branch,percentage:x.rate===null?null:Number(x.rate)*100,commission:x.commission}))},'PUT');
    setEdit(updated);await reload();setMessage('Cambios guardados. El estado queda pendiente de envío.');
  });}
  async function changeStatus(row:Statement,next:'pendiente'|'pagado') {
    const prompt=next==='pagado'?`¿Registrar como pagado el total de $${money(row.total)} ${row.currency} de ${row.name}? También se liquidarán los saldos anteriores incluidos.`:'¿Reabrir este estado como Pendiente de envío? Los saldos anteriores ya liquidados conservarán su pago.';
    if(!window.confirm(prompt))return;
    await run('status',async()=>{await statementAction(`${row.id}/status`,{revision:row.revision,status:next});await reload();if(edit?.id===row.id)setEdit(await getStatement(row.id));setMessage('Estatus actualizado.');});
  }
  async function resolveDelivery(row:Statement,delivered:boolean) {
    if(!window.confirm(delivered?'¿Verificaste en tu correo que el estado sí fue enviado?':'¿Verificaste en tu correo que el estado NO fue enviado? Se habilitará un nuevo intento.'))return;
    await run('resolve',async()=>{await statementAction(`${row.id}/resolve-delivery`,{revision:row.revision,delivered});await reload();setEdit(await getStatement(row.id));});
  }
  async function sendAll() {
    if(!targets)return;setBusy('send');setError('');setSendResults([]);
    for(const row of targets) {
      if(!row.prospector_active){setSendResults(prev=>[...prev,{name:row.name,result:'Prospectador inactivo: envío bloqueado'}]);continue;}
      try {await statementAction(`${row.id}/send`,{revision:row.revision,resend:row.status==='enviado'});setSendResults(prev=>[...prev,{name:row.name,result:'Enviado'}]);}
      catch(e) {setSendResults(prev=>[...prev,{name:row.name,result:e instanceof Error?e.message:'Error de envío'}]);}
    }
    try{await reload();}catch{setError('Actualiza la página para consultar el resultado guardado.');}
    setBusy('');setTargets(null);setSelected([]);
  }
  return <div className="h-full overflow-y-auto p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header><h1 className="text-3xl font-bold text-white">Estados de Prospectadores</h1><p className="mt-2 text-blue-100">Estados mensuales por prospectador, ajustes y saldos pendientes.</p></header>
    {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</div>}
    {message&&<div role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{message}</div>}
    <section className="rounded-xl bg-white p-5 shadow"><div className="flex flex-wrap items-end gap-4">
      <label className="min-w-56 text-sm font-medium text-slate-700">Periodo<select disabled={!!busy} className={`${input} mt-1`} value={period} onChange={e=>{setPeriod(e.target.value);setSelected([]);}}>{data.periods.map(p=><option key={p.id} value={p.id}>{month(p.month)}</option>)}</select></label>
      <button className={button} disabled={!period||!!busy} onClick={()=>void generate()}>{busy==='generate'?<Loader2 className="h-4 w-4 animate-spin"/>:<FileText className="h-4 w-4"/>}Generar / actualizar estados</button>
      <button className={secondary} disabled={!!busy} onClick={()=>void run('refresh',reload)}>Actualizar vista</button>
    </div><p className="mt-3 text-sm text-slate-500">Genera con las tres fuentes cargadas y sin excepciones. Actualiza las comisiones de estados pendientes; conserva sus ajustes. Los estados enviados o pagados se mantienen hasta que los reabras.</p>
    {!data.periods.length&&<p className="mt-3 text-amber-700">Crea primero el periodo en Cobranza para prospectadores.</p>}
    <div className="mt-4 flex flex-wrap gap-3 border-t pt-4"><select aria-label="Prospectador para agregar" className={`${input} max-w-md`} value={manual} onChange={e=>setManual(e.target.value)} disabled={!!busy}><option value="">Agregar un prospectador sin comisiones del mes…</option>{data.prospectors.filter(p=>!rows.some(r=>r.prospector_id===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className={secondary} disabled={!manual||!period||!!busy} onClick={()=>void generate(manual)}><Plus className="h-4 w-4"/>Crear estado</button></div></section>
    <div className="grid gap-4 sm:grid-cols-4">{[['Estados',rows.length],['Pendientes de envío',rows.filter(x=>x.status==='pendiente').length],['Enviados',rows.filter(x=>x.status==='enviado').length],['Pagados',rows.filter(x=>x.status==='pagado').length]].map(([label,value])=><div key={label} className="rounded-xl bg-white p-5 shadow"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div>)}</div>
    <section className="overflow-hidden rounded-xl bg-white shadow"><div className="flex flex-wrap gap-3 border-b p-4"><input aria-label="Buscar prospectador" placeholder="Buscar prospectador…" value={filter} onChange={e=>setFilter(e.target.value)} className={`${input} max-w-xs`}/><select aria-label="Filtrar estatus" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className={`${input} max-w-xs`}><option value="">Todos los estatus</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>
    <button className={button} disabled={!!busy||!selectedRows.length} onClick={()=>setTargets(selectedRows)}><Mail className="h-4 w-4"/>Enviar seleccionados ({selectedRows.length})</button>
    <button className={secondary} disabled={!!busy||!rows.some(x=>x.prospector_active && x.status==='pendiente')} onClick={()=>setTargets(rows.filter(x=>x.prospector_active && x.status==='pendiente'))}>Enviar pendientes del mes</button></div>
    <div className="overflow-x-auto"><table className="w-full text-center text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-3"><input aria-label="Seleccionar visibles" type="checkbox" disabled={!!busy||!selectable.length} checked={allSelected} onChange={()=>setSelected(allSelected?selected.filter(id=>!visible.some(x=>x.id===id)):Array.from(new Set([...selected,...selectable.map(x=>x.id)])))}/></th>{['Prospectador','Comisiones','Ajustes','Saldo anterior','Total','Estatus',''].map((x,i)=><th key={i} className="p-3 whitespace-nowrap">{x}</th>)}</tr></thead><tbody className="divide-y">{visible.map(row=><tr key={row.id} className="text-slate-700"><td className="p-3"><input aria-label={`Seleccionar ${row.name}`} type="checkbox" disabled={!row.prospector_active||row.status==='pagado'||!!busy} checked={row.prospector_active && selected.includes(row.id)} onChange={()=>setSelected(selected.includes(row.id)?selected.filter(x=>x!==row.id):[...selected,row.id])}/></td><td className="p-3"><button className="text-left font-semibold text-blue-700" disabled={!!busy} onClick={()=>void open(row.id)}>{row.name}</button><p className={`mt-1 text-xs ${row.recipient?'text-slate-500':'text-amber-700'}`}>{row.recipient||'Falta correo'}</p>{!row.prospector_active&&<p className="mt-1 text-xs text-amber-700">Prospectador inactivo · Envío bloqueado</p>}</td>{[row.commission,row.adjustment_total,row.carry_total,row.total].map((x,i)=><td key={i} className="p-3 whitespace-nowrap">${money(x)}{i===3&&<span className="ml-1 text-xs">{row.currency}</span>}</td>)}<td className="p-3"><span className={`whitespace-nowrap rounded-full px-2 py-1 text-xs ${row.status==='pagado'?'bg-emerald-100 text-emerald-800':row.status==='enviado'?'bg-blue-100 text-blue-800':'bg-amber-100 text-amber-800'}`}>{labels[row.status]}</span>{['sending','uncertain'].includes(row.delivery_state)&&<p className="mt-2 text-xs text-red-700">Envío por verificar</p>}</td><td className="p-3"><button className={secondary} disabled={!!busy} onClick={()=>void open(row.id)}>Ver / editar</button></td></tr>)}{!visible.length&&<tr><td colSpan={8} className="p-12 text-center text-slate-500">No hay estados para mostrar. Genera los estados del periodo para comenzar.</td></tr>}</tbody></table></div></section>
    {sendResults.length>0&&<section className="rounded-xl bg-white p-5"><h2 className="font-bold text-slate-900">Resultado de los envíos</h2>{sendResults.map((x,i)=><p className={`mt-2 text-sm ${x.result==='Enviado'?'text-emerald-700':'text-red-700'}`} key={i}>{x.name}: {x.result}</p>)}</section>}
    {edit&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><section className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-white text-slate-900 shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between border-b bg-white p-5"><div><h2 className="text-xl font-bold">{edit.name}</h2><p className="text-sm text-slate-500">{month(edit.month)} · {labels[edit.status]} · {edit.currency}</p></div><button aria-label="Cerrar estado" disabled={!!busy} onClick={()=>setEdit(null)}><X/></button></header><div className="space-y-5 p-5">
      {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}{message&&<p className="text-emerald-700">{message}</p>}
      <div className="flex flex-wrap items-center gap-3"><strong className="mr-auto text-xl">Total guardado: ${money(edit.total)} {edit.currency}</strong>{(['pdf','xlsx'] as const).map(format=><button key={format} disabled={!!busy} className={secondary} onClick={()=>void run('download',()=>downloadStatement(edit.id,format))}><Download className="h-4 w-4"/>{format.toUpperCase()} guardado</button>)}<button className={secondary} disabled={!!busy} onClick={()=>void changeStatus(edit,edit.status==='pagado'?'pendiente':'pagado')}>{edit.status==='pagado'?'Reabrir estado':'Marcar pagado'}</button></div>
      {edit.carry.length>0&&<div className="rounded-lg bg-blue-50 p-4"><h3 className="font-semibold">Saldo anterior: ${money(edit.carry_total)}</h3>{edit.carry.map(x=><p className="mt-1 text-sm" key={x.id}>{month(x.month)}: ${money(Number(x.amount)+Number(x.vat||0))}</p>)}<p className="mt-2 text-xs">Marcar pagado liquida también estos saldos. Se arrastra cada importe una sola vez.</p></div>}
      {!edit.prospector_active&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Prospectador inactivo. No se permite enviar ni reenviar este estado.</p>}
      <label className="block text-sm font-semibold">Correo del destinatario<input type="email" className={`${input} mt-1`} disabled={!!busy||edit.status==='pagado'} value={edit.recipient} onChange={e=>setEdit({...edit,recipient:e.target.value})}/></label>
      <div className="overflow-x-auto"><table className="w-full text-center text-sm"><thead className="bg-slate-50"><tr>{['Póliza','Fecha','Aseguradora','Ramo','%','Comisión','IVA','Total'].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{edit.lines.filter(x=>!x.manual).map((x,i)=><tr key={i}><td className="p-2">{x.policy}</td><td className="p-2 whitespace-nowrap">{x.date}</td><td className="p-2">{x.insurer.toLowerCase()==='metlife'?'MetLife':x.insurer.charAt(0).toUpperCase()+x.insurer.slice(1).toLowerCase()}</td><td className="p-2">{x.branch}</td><td className="p-2">{Math.trunc(Number(x.rate)*100)}%</td><td className="p-2">${money(x.commission)}</td><td className="p-2">${money(x.vat)}</td><td className="p-2">${money(x.total)}</td></tr>)}</tbody></table></div>
      <div><h3 className="font-bold">Comisiones de pólizas agregadas manualmente</h3>
      <p className="mt-1 text-sm text-slate-500">Captura la comisión que corresponde al prospectador, sin IVA. Se agregará IVA del 16%. El porcentaje es informativo y opcional; no se vuelve a aplicar al importe. Estas comisiones se conservan al actualizar el periodo.</p>
      {edit.lines.map((x,i)=>x.manual&&<div key={x.id||i} className="mt-3 grid gap-3 rounded-lg border p-3 sm:grid-cols-3">
        {(['policy','date','insurer','branch','commission'] as const).map(key=><label key={key} className="text-sm font-semibold">{{policy:'Póliza',date:'Fecha',insurer:'Aseguradora',branch:'Ramo',commission:'Comisión sin IVA'}[key]}<input disabled={!!busy||edit.status==='pagado'} className={input} type={key==='date'?'date':key==='commission'?'number':'text'} step={key==='commission'?'0.01':undefined} value={x[key]} onChange={e=>setEdit({...edit,lines:edit.lines.map((line,j)=>j===i?{...line,[key]:e.target.value}:line)})}/></label>)}
        <label className="text-sm font-semibold">Porcentaje (opcional)<input disabled={!!busy||edit.status==='pagado'} className={input} type="number" min="0.000001" max="100" step="any" value={x.rate===null?'':Number(x.rate)*100} onChange={e=>setEdit({...edit,lines:edit.lines.map((line,j)=>j===i?{...line,rate:e.target.value===''?null:String(Number(e.target.value)/100)}:line)})}/></label>
        <p className="text-sm">IVA: ${money(Math.sign(Number(x.commission||0))*Math.round(Math.abs(Number(x.commission||0))*16+1e-8)/100)}</p>
        <button className={secondary} disabled={!!busy||edit.status==='pagado'} onClick={()=>setEdit({...edit,lines:edit.lines.filter((_,j)=>j!==i)})}>Eliminar comisión</button>
      </div>)}
      <button className={secondary+' mt-3'} disabled={!!busy||edit.status==='pagado'} onClick={()=>setEdit({...edit,lines:[...edit.lines,{manual:true,policy:'',date:'',insurer:'',branch:'',rate:null,commission:'0.00',vat:'0.00',total:'0.00'}]})}><Plus className="h-4 w-4"/>Agregar comisión de póliza</button></div>
      <div><h3 className="font-bold">Ajustes manuales y saldo inicial</h3><p className="mt-1 text-sm text-slate-500">Ingresa el importe sin IVA. A este monto se le incluirá el IVA (16%). Positivo aumenta el saldo; negativo lo reduce.</p>{edit.adjustments.map((x,i)=><div className="mt-3 flex gap-2" key={i}><input aria-label={`Concepto ${i+1}`} disabled={!!busy||edit.status==='pagado'} className={input} value={x.concept} placeholder="Saldo pendiente anterior / Corrección de póliza…" onChange={e=>setEdit({...edit,adjustments:edit.adjustments.map((a,j)=>j===i?{...a,concept:e.target.value}:a)})}/><input aria-label={`Importe ${i+1}`} disabled={!!busy||edit.status==='pagado'} className={`${input} max-w-40`} type="number" step="0.01" value={x.amount} onChange={e=>setEdit({...edit,adjustments:edit.adjustments.map((a,j)=>j===i?{...a,amount:e.target.value}:a)})}/><button className={secondary} disabled={!!busy||edit.status==='pagado'} onClick={()=>setEdit({...edit,adjustments:edit.adjustments.filter((_,j)=>j!==i),lines:[...edit.lines,{manual:true,policy:x.concept,date:'',insurer:'',branch:'',rate:null,commission:x.amount,vat:'0.00',total:'0.00'}]})}>Convertir en comisión</button><button aria-label="Eliminar ajuste" className={secondary} disabled={!!busy||edit.status==='pagado'} onClick={()=>setEdit({...edit,adjustments:edit.adjustments.filter((_,j)=>j!==i)})}><X className="h-4 w-4"/></button></div>)}<button className={`${secondary} mt-3`} disabled={!!busy||edit.status==='pagado'} onClick={()=>setEdit({...edit,adjustments:[...edit.adjustments,{concept:'',amount:'0.00'}]})}><Plus className="h-4 w-4"/>Agregar ajuste</button><p className="mt-3 font-semibold">Total con los ajustes del formulario: ${money(edit.lines.reduce((sum,x)=>sum+(x.manual?Number(x.commission||0)+Math.sign(Number(x.commission||0))*Math.round(Math.abs(Number(x.commission||0))*16+1e-8)/100:Number(x.total)),0)+Number(edit.carry_total)+edit.adjustments.reduce((a,x)=>a+Number(x.amount||0)+Math.sign(Number(x.amount||0))*Math.round(Math.abs(Number(x.amount||0))*16+1e-8)/100,0))}</p></div>
      <label className="block text-sm font-semibold">Notas visibles en el estado<textarea maxLength={4000} className={`${input} mt-1`} disabled={!!busy||edit.status==='pagado'} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>
      {['sending','uncertain'].includes(edit.delivery_state)&&<div className="rounded-lg bg-amber-50 p-4"><p className="text-sm">{edit.delivery_error||'Hay un envío en curso o sin confirmar. Comprueba el correo enviado antes de reintentar.'}</p><div className="mt-3 flex gap-2"><button className={secondary} disabled={!!busy} onClick={()=>void resolveDelivery(edit,true)}>Verifiqué que sí se envió</button><button className={secondary} disabled={!!busy} onClick={()=>void resolveDelivery(edit,false)}>Verifiqué que no se envió</button></div></div>}
      <details className="text-sm"><summary className="cursor-pointer font-semibold">Historial de cambios</summary>{edit.history.slice().reverse().map((h,i)=><p className="mt-2 text-slate-500" key={i}>{h.at.slice(0,16).replace('T',' ')} UTC · {h.actor} · {h.action.replaceAll('_',' ')}</p>)}</details>
      <div className="sticky bottom-0 flex flex-wrap gap-3 border-t bg-white py-4"><button className={button} disabled={!!busy||edit.status==='pagado'||edit.delivery_state==='sending'} onClick={()=>void save()}>{busy==='save'?'Guardando…':'Guardar cambios'}</button><button className={secondary} disabled={!!busy||!edit.prospector_active||edit.status==='pagado'} onClick={()=>{const saved=data.statements.find(x=>x.id===edit.id);if(saved && edit.prospector_active){setEdit(null);setTargets([{...saved,prospector_active:edit.prospector_active}]);}}}><Mail className="h-4 w-4"/>Enviar versión guardada</button><p className="self-center text-xs text-slate-500">Guarda antes de descargar o enviar. Editar un estado enviado lo deja pendiente de envío.</p></div>
    </div></section></div>}
    {targets&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6 text-slate-900"><h2 className="text-xl font-bold">Revisar envío de estados</h2><p className="mt-2 text-sm text-slate-600">Cada prospectador recibirá únicamente su estado guardado en PDF y Excel. Se usará tu cuenta de Configuración de Mail. Los estados ya enviados se reenviarán si aparecen en esta lista.</p><div className="my-4 divide-y">{targets.map(x=><div key={x.id} className="py-3"><p className="font-semibold">{x.name} · ${money(x.total)} {x.currency}</p><p className={`text-sm ${!x.recipient?'text-red-700':'text-slate-600'}`}>{x.recipient||'Falta correo: edita el estado antes de enviar.'} · {labels[x.status]}</p>{['sending','uncertain'].includes(x.delivery_state)&&<p className="text-sm text-red-700">Primero resuelve el envío anterior desde Ver / editar.</p>}</div>)}</div><p className="mb-3 text-sm">Mantén esta página abierta hasta que terminen los envíos.</p>{busy==='send'&&<p role="status" className="mb-3 text-blue-700">Procesados {sendResults.length} de {targets.length}…</p>}<div className="flex gap-3"><button className={secondary} disabled={!!busy} onClick={()=>setTargets(null)}>Cancelar</button><button className={button} disabled={!!busy||targets.some(x=>!x.prospector_active||!x.recipient||['sending','uncertain'].includes(x.delivery_state))} onClick={()=>void sendAll()}>Confirmar envío de {targets.length} estados</button></div></section></div>}
  </div></div>;
}
