'use client';

import { useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, Check, FileSearch, Landmark, Loader2, Plus, RefreshCw, Search, Trash2, Upload, X } from 'lucide-react';
import {
  Budget, Company, FinanceInvoice, FinanceMovement, FinanceOverview, Projection, RecurringGroup, Rule,
  applyRule, cancelProjection, createProjection, createRule, decideRecurring, deleteRule,
  exportMovements, getBudgets, getCashFlow, getFinanceOverview, getInvoiceSuggestions, getInvoices, getMovements, getRecurring, getRules,
  matchInvoice, previewIngestion, previewRule, publishIngestion, revertRule, scanInvoices, syncSources, updateMovement, upsertBudget,
} from '@/modules/finanzas/service';

const TABS = ['Resumen', 'Movimientos', 'Recurrentes', 'Facturas', 'Flujo y presupuesto', 'Clasificación'] as const;
type Tab = typeof TABS[number];
const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 });
const dateFormat = new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium' });

function ErrorMessage({ text }: { text: string }) {
  return text ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{text}</div> : null;
}

function Empty({ children }: { children: React.ReactNode }) {
  return <div className="flex min-h-52 items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-sm text-slate-500">{children}</div>;
}

function Kpi({ label, value, tone = 'slate' }: { label: string; value: string; tone?: 'slate' | 'green' | 'amber' | 'red' }) {
  const colors = { slate: 'border-slate-200', green: 'border-emerald-300', amber: 'border-amber-300', red: 'border-red-300' };
  return <div className={`rounded-xl border-l-4 bg-white p-4 shadow-sm ${colors[tone]}`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div>;
}

export function FinanceView({ initialOverview }: { initialOverview: FinanceOverview }) {
  const [tab, setTab] = useState<Tab>('Resumen');
  const [company, setCompany] = useState<Company>('CONSOLIDADO');
  const [overview, setOverview] = useState(initialOverview);
  const [movements, setMovements] = useState<FinanceMovement[]>([]);
  const [movementTotal, setMovementTotal] = useState(0);
  const [search, setSearch] = useState('');
  const [recurring, setRecurring] = useState<RecurringGroup[]>([]);
  const [invoices, setInvoices] = useState<FinanceInvoice[]>([]);
  const [invoiceFolder, setInvoiceFolder] = useState(false);
  const [projections, setProjections] = useState<Projection[]>([]);
  const [budgets, setBudgets] = useState<Budget[]>([]);
  const [rules, setRules] = useState<Rule[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [uploadOpen, setUploadOpen] = useState(false);

  async function load(activeTab = tab, activeCompany = company) {
    setLoading(true); setError('');
    try {
      if (activeTab === 'Resumen') setOverview(await getFinanceOverview(activeCompany));
      if (activeTab === 'Movimientos') { const response = await getMovements(activeCompany, search); setMovements(response.items); setMovementTotal(response.total); }
      if (activeTab === 'Recurrentes') setRecurring((await getRecurring(activeCompany)).items);
      if (activeTab === 'Facturas') { const response = await getInvoices(); setInvoices(response.items); setInvoiceFolder(response.folder_available); }
      if (activeTab === 'Flujo y presupuesto') { const [flow, budget] = await Promise.all([getCashFlow(activeCompany), getBudgets(activeCompany)]); setProjections(flow.items); setBudgets(budget.items); }
      if (activeTab === 'Clasificación') setRules((await getRules()).items);
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo cargar Finanzas'); }
    finally { setLoading(false); }
  }

  function chooseTab(value: Tab) { setTab(value); void load(value, company); }
  function chooseCompany(value: Company) { setCompany(value); void load(tab, value); }

  return <div className="flex h-full min-h-0 flex-col gap-4 text-slate-900">
    <div className="flex flex-wrap items-start justify-between gap-3">
      <div><h1 className="flex items-center gap-2 text-2xl font-bold text-white"><Landmark className="h-6 w-6" />Finanzas</h1><p className="text-sm text-blue-100">Salud financiera, conciliación y planeación con trazabilidad a la fuente.</p></div>
      <div className="flex gap-2">
        <button onClick={() => setUploadOpen(true)} className="flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2 text-sm font-bold text-white hover:bg-emerald-600"><Upload className="h-4 w-4" />Cargar estados</button>
        <button onClick={() => load()} disabled={loading} className="rounded-lg border border-white/30 bg-white/10 p-2.5 text-white hover:bg-white/20" title="Actualizar"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button>
      </div>
    </div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-white p-2 shadow">
      <div className="flex max-w-full gap-1 overflow-x-auto">{TABS.map((item) => <button key={item} onClick={() => chooseTab(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${tab === item ? 'bg-emerald-600 text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{item}</button>)}</div>
      <div className="flex rounded-lg bg-slate-100 p-1">{(['CONSOLIDADO', 'TLA', 'TS'] as Company[]).map((item) => <button key={item} onClick={() => chooseCompany(item)} className={`rounded-md px-3 py-1.5 text-xs font-bold ${company === item ? 'bg-white text-emerald-700 shadow' : 'text-slate-500'}`}>{item === 'CONSOLIDADO' ? 'Consolidado' : item}</button>)}</div>
    </div>
    <ErrorMessage text={error} />
    <div className="min-h-0 flex-1 overflow-auto rounded-2xl bg-white/95 p-4 shadow-xl md:p-6">
      {loading && <div className="mb-3 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Actualizando información…</div>}
      {tab === 'Resumen' && <Summary overview={overview} onSync={async () => { setLoading(true); try { await syncSources(); await load('Resumen', company); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo sincronizar'); } finally { setLoading(false); } }} />}
      {tab === 'Movimientos' && <Movements items={movements} total={movementTotal} company={company} search={search} setSearch={setSearch} onSearch={() => load('Movimientos')} onSaved={(saved) => setMovements((current) => current.map((item) => item.id === saved.id ? saved : item))} />}
      {tab === 'Recurrentes' && <Recurring items={recurring} onDecide={async (fingerprint, status) => { await decideRecurring(fingerprint, status); await load('Recurrentes'); }} />}
      {tab === 'Facturas' && <Invoices items={invoices} folderAvailable={invoiceFolder} onScan={async () => { const result = await scanInvoices(); if (result.message) setError(result.message); await load('Facturas'); }} onRefresh={() => load('Facturas')} />}
      {tab === 'Flujo y presupuesto' && <CashFlow items={projections} budgets={budgets} company={company} onRefresh={() => load('Flujo y presupuesto')} />}
      {tab === 'Clasificación' && <Rules items={rules} onRefresh={() => load('Clasificación')} setError={setError} />}
    </div>
    {uploadOpen && <UploadWizard onClose={() => setUploadOpen(false)} onPublished={async () => { setUploadOpen(false); await load('Resumen'); }} />}
  </div>;
}

function Summary({ overview, onSync }: { overview: FinanceOverview; onSync: () => Promise<void> }) {
  const k = overview.kpis;
  return <div className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <Kpi label="Efectivo activo" value={money.format(k.active_cash)} tone="green" /><Kpi label="Pasivo tarjetas" value={money.format(k.credit_liability)} tone="red" /><Kpi label="Flujo neto del mes" value={money.format(k.net_flow_month)} tone={k.net_flow_month >= 0 ? 'green' : 'red'} /><Kpi label="Sin clasificar" value={String(k.unclassified)} tone={k.unclassified ? 'amber' : 'green'} /><Kpi label="Facturas pendientes" value={String(k.invoice_gaps)} tone={k.invoice_gaps ? 'amber' : 'green'} />
    </div>
    <div className="grid gap-4 xl:grid-cols-[2fr,1fr]">
      <section className="rounded-xl border border-slate-200 p-4"><h2 className="font-bold">Entradas y salidas</h2>{overview.monthly.length ? <div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={overview.monthly}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#059669" stopOpacity={.35}/><stop offset="95%" stopColor="#059669" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip formatter={(value) => money.format(Number(value))} /><Area type="monotone" dataKey="entries" name="Entradas" stroke="#059669" fill="url(#income)" /><Area type="monotone" dataKey="exits" name="Salidas" stroke="#dc2626" fill="#fecaca" /></AreaChart></ResponsiveContainer></div> : <Empty>Sin movimientos indexados para graficar.</Empty>}</section>
      <section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><h2 className="font-bold">Fuentes</h2><button onClick={onSync} className="text-xs font-bold text-emerald-700 hover:underline">Sincronizar</button></div><div className="mt-3 space-y-2">{overview.sources.length ? overview.sources.map((source) => <div key={source.key} className="rounded-lg bg-slate-50 p-3"><div className="flex items-center justify-between"><span className="font-semibold">{source.company} · {source.bank}</span><span className={`h-2.5 w-2.5 rounded-full ${source.available ? 'bg-emerald-500' : 'bg-amber-500'}`} /></div><p className="mt-1 text-xs text-slate-500">{source.available ? `${source.row_count} movimientos · ${source.last_synced_at ? dateFormat.format(new Date(source.last_synced_at)) : 'pendiente de sincronizar'}` : source.error || 'Fuente no disponible'}</p></div>) : <p className="text-sm text-slate-500">Pulsa Sincronizar para registrar el estado de las fuentes.</p>}</div></section>
    </div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Entradas del mes" value={money.format(k.entries_month)} /><Kpi label="Salidas del mes" value={money.format(k.exits_month)} /><Kpi label="Impuestos del mes" value={money.format(k.tax_month)} /><Kpi label="Compromisos futuros" value={money.format(k.future_commitments)} /></div>
  </div>;
}

function Movements({ items, total, company, search, setSearch, onSearch, onSaved }: { items: FinanceMovement[]; total: number; company: Company; search: string; setSearch: (value: string) => void; onSearch: () => void; onSaved: (item: FinanceMovement) => void }) {
  const [editing, setEditing] = useState<FinanceMovement | null>(null);
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex w-full max-w-xl"><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && onSearch()} placeholder="Buscar descripción, contraparte, referencia o ID" className="min-w-0 flex-1 rounded-l-lg border border-slate-300 px-3 py-2 text-sm" /><button onClick={onSearch} className="rounded-r-lg bg-slate-900 px-3 text-white"><Search className="h-4 w-4" /></button></div><div className="flex items-center gap-3"><span className="text-sm text-slate-500">{total.toLocaleString('es-MX')} movimientos</span><button onClick={() => exportMovements(company, search)} className="rounded-lg border px-3 py-2 text-xs font-bold">Exportar vista</button></div></div>
    {items.length ? <div className="overflow-x-auto rounded-xl border"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">Fecha</th><th>Empresa/Banco</th><th>Descripción</th><th>Categoría</th><th className="text-right">Importe</th><th>Factura</th><th>Fuente</th></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id} onClick={() => setEditing(item)} className="cursor-pointer hover:bg-emerald-50"><td className="px-3 py-3">{dateFormat.format(new Date(`${item.fecha_operacion}T12:00:00`))}</td><td>{item.empresa} · {item.banco}</td><td className="max-w-sm"><p className="truncate font-medium">{item.descripcion_original}</p><p className="truncate text-xs text-slate-500">{item.contraparte || item.referencia}</p></td><td>{item.categoria || <span className="text-amber-700">Sin clasificar</span>}</td><td className={`text-right font-semibold ${item.importe_neto < 0 ? 'text-red-600' : 'text-emerald-700'}`}>{money.format(item.importe_neto)}</td><td>{item.factura_uuid ? <Check className="h-4 w-4 text-emerald-600" /> : item.requiere_factura ? <AlertTriangle className="h-4 w-4 text-amber-500" /> : '—'}</td><td className="text-xs text-slate-500">{item.archivo_fuente || '—'}{item.pagina_fuente ? ` · p.${item.pagina_fuente}` : ''}</td></tr>)}</tbody></table></div> : <Empty>No hay movimientos. Sincroniza las fuentes o revisa los filtros.</Empty>}
    {editing && <MovementEditor item={editing} onClose={() => setEditing(null)} onSave={async (payload) => { const response = await updateMovement(editing.id, payload); onSaved(response.movement); setEditing(null); }} />}
  </div>;
}

function MovementEditor({ item, onClose, onSave }: { item: FinanceMovement; onClose: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) {
  const [category, setCategory] = useState(item.categoria); const [subcategory, setSubcategory] = useState(item.subcategoria); const [saving, setSaving] = useState(false);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-lg font-bold">Clasificar movimiento</h2><p className="mt-1 text-sm text-slate-500">{item.descripcion_original}</p></div><button onClick={onClose}><X /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Categoría<input value={category} onChange={(e) => setCategory(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="text-sm font-semibold">Subcategoría<input value={subcategory} onChange={(e) => setSubcategory(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" /></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={saving || !category.trim()} onClick={async () => { setSaving(true); await onSave({ categoria: category.trim(), subcategoria: subcategory.trim() || null }); setSaving(false); }} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white disabled:opacity-50">Guardar</button></div></div></div>;
}

function Recurring({ items, onDecide }: { items: RecurringGroup[]; onDecide: (fingerprint: string, status: string) => Promise<void> }) {
  return <div className="space-y-3"><div><h2 className="text-lg font-bold">Detección explicable de recurrentes</h2><p className="text-sm text-slate-500">La decisión humana se conserva y prevalece sobre futuras sugerencias.</p></div>{items.length ? items.map((item) => <div key={item.fingerprint} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-semibold">{item.label}</p><p className="text-xs text-slate-500">{item.company} · {item.occurrences} movimientos en {item.months} meses · promedio {money.format(item.average_amount)}</p><p className="mt-1 text-xs text-slate-400">{item.basis}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status === 'confirmado' ? 'bg-emerald-100 text-emerald-700' : item.status === 'descartado' ? 'bg-slate-100 text-slate-600' : 'bg-amber-100 text-amber-700'}`}>{item.status}</span><button onClick={() => onDecide(item.fingerprint, 'confirmado')} className="rounded-lg border border-emerald-300 px-3 py-1.5 text-xs font-bold text-emerald-700">Confirmar</button><button onClick={() => onDecide(item.fingerprint, 'descartado')} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Descartar</button></div></div>) : <Empty>No hay patrones recurrentes suficientes con la información indexada.</Empty>}</div>;
}

function Invoices({ items, folderAvailable, onScan, onRefresh }: { items: FinanceInvoice[]; folderAvailable: boolean; onScan: () => Promise<void>; onRefresh: () => Promise<void> }) {
  const [suggestions, setSuggestions] = useState<{ invoice: FinanceInvoice; items: Array<{ movement: FinanceMovement; confidence: number; rationale: string }> } | null>(null);
  async function suggest(invoice: FinanceInvoice) {
    const response = await getInvoiceSuggestions(invoice.id);
    setSuggestions({ invoice, items: response.items });
  }
  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Facturas y conciliación</h2><p className="text-sm text-slate-500">El XML aporta datos CFDI; un PDF solo se conserva como evidencia y no acredita validez fiscal.</p></div><button onClick={onScan} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white"><FileSearch className="h-4 w-4" />Indexar carpeta</button></div>
    {!folderAvailable && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">La carpeta configurada de facturas no está montada en este servidor.</div>}
    {items.length ? <div className="overflow-x-auto rounded-xl border"><table className="min-w-[950px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">Archivo</th><th>UUID</th><th>Emisor → receptor</th><th>Total</th><th>Estatus</th><th /></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-3 py-3"><p className="font-medium">{item.filename}</p>{item.parse_error && <p className="max-w-sm text-xs text-amber-700">{item.parse_error}</p>}</td><td className="font-mono text-xs">{item.uuid || '—'}</td><td>{item.issuer_rfc || '—'} → {item.receiver_rfc || '—'}</td><td>{item.total == null ? '—' : money.format(item.total)}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{item.status}</span></td><td><button disabled={!item.total || !item.issued_at || item.status === 'conciliada'} onClick={() => suggest(item)} className="rounded-lg border px-3 py-1.5 text-xs font-bold disabled:opacity-40">Sugerir</button></td></tr>)}</tbody></table></div> : <Empty>No hay facturas indexadas.</Empty>}
    {suggestions && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="max-h-[80vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h3 className="text-lg font-bold">Sugerencias de conciliación</h3><p className="text-sm text-slate-500">{suggestions.invoice.filename}</p></div><button onClick={() => setSuggestions(null)}><X /></button></div><div className="mt-4 space-y-2">{suggestions.items.length ? suggestions.items.map((item) => <div key={item.movement.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-semibold">{item.movement.descripcion_original}</p><p className="text-xs text-slate-500">{item.movement.fecha_operacion} · {money.format(item.movement.importe_neto)} · {item.rationale}</p></div><button onClick={async () => { await matchInvoice(suggestions.invoice.id, item.movement.id); setSuggestions(null); await onRefresh(); }} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Confirmar {item.confidence}%</button></div>) : <Empty>No hay candidatos con al menos 50% de confianza.</Empty>}</div></div></div>}
  </div>;
}

function CashFlow({ items, budgets, company, onRefresh }: { items: Projection[]; budgets: Budget[]; company: Company; onRefresh: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const total = useMemo(() => items.reduce((sum, item) => sum + item.amount, 0), [items]);
  return <div className="space-y-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Flujo futuro y presupuesto</h2><p className="text-sm text-slate-500">Real histórico más compromisos futuros. Las proyecciones nunca se mezclan con movimientos bancarios reales.</p></div><button disabled={company === 'CONSOLIDADO'} onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40"><Plus className="h-4 w-4" />Proyección</button></div><Kpi label="Compromisos proyectados" value={money.format(total)} tone={total < 0 ? 'amber' : 'green'} />{items.length ? <div className="space-y-2">{items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">{item.concept}</p><p className="text-xs text-slate-500">{item.company} · {dateFormat.format(new Date(`${item.due_date}T12:00:00`))} · escenario {item.scenario}</p></div><div className="flex items-center gap-3"><span className={`font-bold ${item.amount < 0 ? 'text-red-600' : 'text-emerald-700'}`}>{money.format(item.amount)}</span><button onClick={async () => { await cancelProjection(item.id); await onRefresh(); }} title="Cancelar"><Trash2 className="h-4 w-4 text-slate-400" /></button></div></div>)}</div> : <Empty>No hay compromisos proyectados en los próximos 90 días.</Empty>}
    <section><h3 className="mb-2 font-bold">Presupuesto mensual vs. real</h3>{budgets.length ? <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Empresa</th><th>Categoría</th><th className="text-right">Presupuesto</th><th className="text-right">Real</th><th className="pr-3 text-right">Variación</th></tr></thead><tbody className="divide-y">{budgets.map((item) => <tr key={item.id}><td className="p-3">{item.company}</td><td>{item.category}</td><td className="text-right">{money.format(item.budget)}</td><td className="text-right">{money.format(item.actual)}</td><td className={`pr-3 text-right font-semibold ${item.variance < 0 ? 'text-red-600' : 'text-emerald-700'}`}>{money.format(item.variance)}</td></tr>)}</tbody></table></div> : <Empty>{company === 'CONSOLIDADO' ? 'Selecciona TLA o TS para capturar presupuesto.' : <BudgetQuickForm company={company} onCreated={onRefresh} />}</Empty>}</section>
    {open && <ProjectionModal company={company as 'TLA' | 'TS'} onClose={() => setOpen(false)} onCreated={async () => { setOpen(false); await onRefresh(); }} />}
  </div>;
}

function BudgetQuickForm({ company, onCreated }: { company: 'TLA' | 'TS'; onCreated: () => Promise<void> }) {
  const [category, setCategory] = useState(''); const [amount, setAmount] = useState(''); const month = new Date().toISOString().slice(0, 7) + '-01';
  return <div className="w-full max-w-md"><p className="mb-3">Crea la primera partida del mes para {company}.</p><div className="flex gap-2"><input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Categoría" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-slate-900" /><input value={amount} onChange={(e) => setAmount(e.target.value)} type="number" placeholder="Monto" className="w-28 rounded-lg border px-3 py-2 text-slate-900" /><button disabled={!category || !amount} onClick={async () => { await upsertBudget({ company, month, category, amount: Number(amount) }); await onCreated(); }} className="rounded-lg bg-emerald-600 px-3 py-2 font-bold text-white disabled:opacity-40">Guardar</button></div></div>;
}

function ProjectionModal({ company, onClose, onCreated }: { company: 'TLA' | 'TS'; onClose: () => void; onCreated: () => Promise<void> }) {
  const [concept, setConcept] = useState(''); const [dueDate, setDueDate] = useState(''); const [amount, setAmount] = useState('');
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-lg font-bold">Nueva proyección · {company}</h2><button onClick={onClose}><X /></button></div><div className="mt-5 space-y-3"><input value={concept} onChange={(e) => setConcept(e.target.value)} placeholder="Concepto" className="w-full rounded-lg border px-3 py-2" /><input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} className="w-full rounded-lg border px-3 py-2" /><input type="number" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Importe (negativo para salida)" className="w-full rounded-lg border px-3 py-2" /></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button><button onClick={async () => { await createProjection({ company, concept, due_date: dueDate, amount: Number(amount), scenario: 'base' }); await onCreated(); }} disabled={!concept || !dueDate || !amount} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white disabled:opacity-40">Crear</button></div></div></div>;
}

function Rules({ items, onRefresh, setError }: { items: Rule[]; onRefresh: () => Promise<void>; setError: (value: string) => void }) {
  const [open, setOpen] = useState(false); const [preview, setPreview] = useState<{ rule: Rule; total: number; conflicts: number } | null>(null);
  return <div className="space-y-4"><div className="flex justify-between"><div><h2 className="text-lg font-bold">Reglas de clasificación</h2><p className="text-sm text-slate-500">Previsualiza coincidencias y conflictos antes de aplicar. La fuente original no se modifica.</p></div><button onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white"><Plus className="h-4 w-4" />Regla</button></div>{items.length ? <div className="space-y-2">{items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-semibold">{item.priority}. {item.name}</p><p className="text-xs text-slate-500">{item.company || 'Todas'} · {item.field} {item.operator.replace('_', ' ')} “{item.value}” → {item.exclusion ? 'Excluir' : `${item.category}${item.subcategory ? ` / ${item.subcategory}` : ''}`}</p></div><div className="flex gap-2"><button onClick={async () => { const result = await previewRule(item.id); setPreview({ rule: item, total: result.total, conflicts: result.conflicts }); }} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Previsualizar</button><button onClick={async () => { try { const result = await revertRule(item.id); setError(`Se restauraron ${result.restored} movimientos.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No hay una ejecución reversible'); } }} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Revertir última</button><button onClick={async () => { await deleteRule(item.id); await onRefresh(); }} className="rounded-lg p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></div></div>)}</div> : <Empty>No hay reglas configuradas.</Empty>}{open && <RuleModal onClose={() => setOpen(false)} onCreated={async () => { setOpen(false); await onRefresh(); }} />}{preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h3 className="text-lg font-bold">Previsualización</h3><p className="mt-3 text-sm"><strong>{preview.total}</strong> movimientos coinciden; <strong>{preview.conflicts}</strong> ya tienen una categoría diferente.</p><p className="mt-2 text-xs text-slate-500">Aplicar actualiza la capa de clasificación y queda registrado en auditoría.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setPreview(null)} className="rounded-lg border px-4 py-2">Cancelar</button><button onClick={async () => { try { const result = await applyRule(preview.rule.id); setPreview(null); setError(`Regla aplicada a ${result.updated} movimientos.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo aplicar'); } }} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">Aplicar</button></div></div></div>}</div>;
}

function RuleModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => Promise<void> }) {
  const [name, setName] = useState(''); const [value, setValue] = useState(''); const [category, setCategory] = useState('');
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-lg font-bold">Nueva regla</h2><button onClick={onClose}><X /></button></div><div className="mt-5 space-y-3"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Nombre" className="w-full rounded-lg border px-3 py-2" /><input value={value} onChange={(e) => setValue(e.target.value)} placeholder="Texto contenido en la descripción" className="w-full rounded-lg border px-3 py-2" /><input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Categoría a asignar" className="w-full rounded-lg border px-3 py-2" /></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button><button onClick={async () => { await createRule({ name, priority: 100, field: 'descripcion_original', operator: 'contiene', value, company: null, category, subcategory: null, enabled: true, exclusion: false }); await onCreated(); }} disabled={!name || !value || !category} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white disabled:opacity-40">Crear</button></div></div></div>;
}

function UploadWizard({ onClose, onPublished }: { onClose: () => void; onPublished: () => Promise<void> }) {
  const [source, setSource] = useState('tla_amex'); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<{ ingestion_id: string; rows: number; new_rows: number; duplicates: number } | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-6"><div><h2 className="text-xl font-bold">Carga guiada de estados</h2><p className="text-sm text-slate-500">Previsualiza, detecta duplicados y confirma antes de tocar el histórico canónico.</p></div><button onClick={onClose}><X /></button></div><div className="space-y-4 p-6"><ErrorMessage text={error} /><label className="block text-sm font-semibold">Fuente<select value={source} onChange={(e) => { setSource(e.target.value); setPreview(null); }} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"><option value="tla_amex">TLA · AMEX</option><option value="tla_bbva">TLA · BBVA</option><option value="tla_banorte">TLA · Banorte</option><option value="ts_bbva">TS · BBVA</option></select></label><label className="block rounded-xl border-2 border-dashed border-slate-300 p-6 text-center"><Upload className="mx-auto h-7 w-7 text-slate-400" /><span className="mt-2 block text-sm font-semibold">{file?.name || 'Seleccionar CSV canónico o estado original'}</span><input type="file" accept=".csv,.pdf" className="sr-only" onChange={(e) => { setFile(e.target.files?.[0] || null); setPreview(null); }} /></label>{preview && <div className="grid grid-cols-3 gap-3"><Kpi label="Filas" value={String(preview.rows)} /><Kpi label="Nuevas" value={String(preview.new_rows)} tone="green" /><Kpi label="Duplicadas" value={String(preview.duplicates)} tone={preview.duplicates ? 'amber' : 'green'} /></div>}<div className="rounded-lg bg-slate-50 p-3 text-xs text-slate-600">Los PDF originales se preservan, pero solo se publican automáticamente cuando existe un parser validado para ese formato. El sistema nunca adivina movimientos bancarios.</div></div><div className="flex justify-end gap-2 border-t p-5"><button onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button>{!preview ? <button disabled={!file || busy} onClick={async () => { if (!file) return; setBusy(true); setError(''); try { setPreview(await previewIngestion(source, file)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo previsualizar'); } finally { setBusy(false); } }} className="rounded-lg bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-40">{busy ? 'Validando…' : 'Previsualizar'}</button> : <button disabled={busy || preview.duplicates > 0 || preview.new_rows === 0} onClick={async () => { setBusy(true); setError(''); try { await publishIngestion(preview.ingestion_id); await onPublished(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo publicar'); } finally { setBusy(false); } }} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white disabled:opacity-40">Confirmar y publicar</button>}</div></div></div>;
}
